### ISSUE TITLE
Upload: Exception in Logs

### ISSUE THREAD

**Issue by philboeselager** [hbz/laser-ygor#283]
Remove the following exception from the log:

2020-09-07 12:12:23,773 [ajp-nio-8009-exec-22] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /ygor/statistic/refreshJobStatus
Cannot invoke method toLowerCase() on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot invoke method toLowerCase() on null object
	at ygor.UploadJob.refreshStatus(UploadJob.groovy:71)
	at ygor.StatisticController$_closure10.doCall(StatisticController.groovy:456)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-07 12:12:24,742 [ajp-nio-8009-exec-33] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /ygor/statistic/refreshJobStatus

**Comment by philboeselager** [comment]
Not reproducible any more. Closing.
